### ISSUE TITLE
Admin Service - Doubt related to admin services.

### ISSUE THREAD

**Issue by NabheetCloud** [sapmentors/sitregcapm#11]
Hello

I believe we have all the entities created. The basic CRUD service comes by default.  In existing XSC application we can see for ODataAdmin we only have events and participant points read only, is the rest of the admin stuff done at database level in existing app or i am missing something here?

Thanks
Nabheet

**Comment by gregorwolf** [comment]
I hope there is a way to avoid a lot of the code duplications that where needed in XSC. I would think we restrict all CRUD operations of the Admin Service to read only. That way the admin could read everything but also can't break anything that has business logic. For the other Roles: Organizer, Participant, Receptionist and Anonymous general business logic should be implemented only once and only specific logic should be added to the specific endpoints.

**Comment by NabheetCloud** [comment]
make sense let admin have a bird eye view read only. Let other roles handle CRUD stuff. Okay Thanks
